apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mytomcat-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mytomcat
      version: 2.7.02
  template:
    metadata:
      labels:
        app: mytomcat
        version: 2.7.02
    spec:
      containers:
      - name: mytomcat-pod
        image: ravidevops26/k8sapp:1
        ports:
        - containerPort: 8080
